### ISSUE TITLE
Code Organization

### ISSUE THREAD

**Issue by deepraj1729** [kfamuuwavwm/XFFF#1]
Hey `@ENNP` , I really liked ur work .
I was reading ur source code and it really isn't organized well.

Plz organize them in this way:
`.db` files in one DB directory,
`.py` files must be in py/ directory
`.html` files in web/ directory
`.png`, `.jpeg` image files in media/ directory
`.sh` (bash scripts must be at the top)

```This will increase the readability and debugging.```

Anyway liked ur work a lot. Have fun ; )

**Comment by kokojop** [comment]
Thank you for leaving me a good issue. I think it's a really good solution.
I'll leave here a link when I'm done editing.

Regards,
kokojop

**Comment by kokojop** [comment]
Hello, deepraj1729
Your issue has been applied to [v2.1.0](https://github.com/kokojop/XFFF/releases/tag/v2.1.0)
Also, added your name to README.md's Thanks to.
Thank you for the good issue.

Regards,
kokojop

**Comment by deepraj1729** [comment]
Thanks a lot @kokojop 
Now it looks great 
I prefer code readability over efficiency first  ; )
